name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG] <describe the bug>"
labels: [bug]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! 🐞

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: e.g., Windows 11, Chrome v123.4

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
      description: Be as detailed as possible.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
